micronaut:
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        keycloak: # <2>
          client-secret: '${OAUTH_CLIENT_SECRET:secret}' # <3>
          client-id: '${OAUTH_CLIENT_ID:frontend}' # <4>
          openid:
            issuer: '${OIDC_ISSUER_DOMAIN:`http://localhost:8180/realms/quarkus/`}' # <5>
    endpoints:
      logout:
        get-allowed: true # <6>
